### ISSUE TITLE
Singleton

### ISSUE THREAD

**Issue by marjanhrzic** [aleksandarzivanovic/vibe#1]
Why is DI singleton?

**Comment by coazivanovic** [comment]
Because we want same class instance where ever we call Di::get($className), and it's not singleton strict, you can pass seconds parameter to Di::get, and it will return new instance.

**Comment by marjanhrzic** [comment]
i was talking about this: 

``` php
 public static function instance() {
    if (false == self::$instance) {
        self::$instance = new self;
    }
    return self::$instance;
}
```

Also, constructor is protected.

**Comment by coazivanovic** [comment]
As I said, we want same instances of classes loaded into Di. 
As you can see there is protected variable $loadedInstances, and with singleton Di, $loadedInstances will be filled where ever we call Di::instance() (except first time). So when we call Di->get(), we will have same instance in one file as in another.

I know I could simply set $loadedInstances as static, but in that case reload method would need to clear $loadedInstances instead of just clearing current Di instance.

**Comment by marjanhrzic** [comment]
https://github.com/domnikl/DesignPatternsPHP/tree/master/More/ServiceLocator

**Comment by coazivanovic** [comment]
constructor is protected, so we could only extend or Di::instance this calss :smile:
